### ISSUE TITLE
What method to import gatsby-source-plone?

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-starter-plone#1]
For local dev `yarn link` I'm using but for updating the package.json with the dependency, since we haven't published our package on npm yet, what'd be the best way to import?

I'm thinking we could use a github import:
```
"gatsby-source-plone": "git+ssh://git@github.com/collective/gatsby-source-plone.git"
```

@datakurre @cekk

**Comment by ajayns** [comment]
Actually, since we have an `npm prepare` script, on installing dependencies, it does the compilation as well.

**Comment by datakurre** [comment]
@ajayns Ok. If git+ssh works, it is ok.

**Comment by ajayns** [comment]
Yes, will make the changes. I hadn't changed thinking maybe we'll ship the npm package soon.
