### ISSUE TITLE
Enable offline and PWA -plugins

### ISSUE THREAD

**Issue by datakurre** [collective/gatsby-starter-plone#14]
Should we enable offline and PWA -plugins by default? Is there any reason not to enable them? (I assume the offline-plugin does cache invalidation right...)

@polyester Opinion, should gatsby-starter-plone come with PWA and offline -features enabled by default?

The current build result: https://collective.github.io/gatsby-starter-plone/

**Comment by polyester** [comment]
I don't have a strong opinion; either enabled by default or commented out (so that enabling it is just a question of uncommenting) is fine by me.

**Comment by tisto** [comment]
Enable by default.
