### ISSUE TITLE
Querying data and displaying in gatsby-site

### ISSUE THREAD

**Issue by ajayns** [collective/gatsby-starter-plone#2]
The next proposed steps in the narrative docs would be basic querying and then proper page creation and such.

So for the first step, I was thinking I'll query for all the PloneFolder in the root and display them at the index. And then illustrate page creation, using template etc by creating pages for all PloneFolder

Opinions? @datakurre @cekk 

PS Currently, I'm using the local docker image as source for the starter, let me know if I'm supposed to wait or change configs to any other sources.

**Comment by datakurre** [comment]
@ajayns Maybe https://plonedemo.kitconcept.com/en ? It has REST API enabled for anonymous users.

I hope @cekk has opinions, because he is also planning training.

My opinions are all around our test project for the source plugin. Eg. front pages are usually special, so it might make sense to define them in ./pages

**Comment by tisto** [comment]
@ajayns feel free to use plonedemo.kitconcept.com. Let me know if there is anything missing. We are happy to add stuff if necessary.

**Comment by ajayns** [comment]
So shall I move forward with this? I'll use plonedemo.kitconcept.com as the source site? @cekk @datakurre

**Comment by datakurre** [comment]
Yes.

**Comment by ajayns** [comment]
Great working on it!

**Comment by cekk** [comment]
@ajayns sorry for the delay.
I don't know if it's better starting with a simple content, for example a page or a news.
Show how to query all of them and how to create a page.
And then, pass to more complex things like folders: querying them and show all folder contents in the view
